### ISSUE TITLE
not working on my case

### ISSUE THREAD

**Issue by geraldvillorente** [rainu/go-command-chain#1]
I am trying to parse nginx-access.log with:
```
cat nginx-access.log | awk -F\" '{print $8}' | awk -F\, '{print $1}' | sort -n | uniq -c | sort -nr | head -10
```

And using this library, I converted the command to:
```
err := cmdchain.Builder().
		Join("tail", outputFile).
		Join("awk", "-F\"", "'{print $8}'").
		Join("awk", "-F\\,", "'{print $1}'").
		Join("sort", "-n").
		Join("uniq", "-c").
		Join("sort", "-fnr").
		Join("head", "-n"+strconv.Itoa(line)).
		Finalize().
		WithOutput(output).
		Run()
```

But I am getting this:
```
one or more command has returned an error: [0 - ; 1 - exit status 2]
```

Any idea?

**Comment by rainu** [comment]
hey .. sorry for late reaction .. i will have a look as soon as possible :)

**Comment by rainu** [comment]
I have tested it locally. An got something similar. 
```one or more command has returned an error: [0 - ; 1 - exit status 1; 2 - exit status 1; 3 - ; 4 - ; 5 - ; 6 - ]```

So let me explain what is going on there. You see an array of errors. That's because you use multiple commands. So each command can have their own error code. So in my case command **nr. 1** has no error, **nr. 2** has exit status 1 and **nr. 2** has exit status 1 and so on.

So in my case (and in yours too) the second command is **awk**. In my case i can fix the issue by replacing ```Join("awk", "-F\"", "'{print $8}'").``` with ```Join("awk", "-F\"", "{print $8}").``` (remove additional single quotes). Why is that so? Because the awk process will got `'{print $8}'` which is not expected by awk (expected: `{print $8}` (wihtout quotes)). The single quotes should be used in case of **bash**! Otherwise the bash will interpret the "$8" by it self and will not give "$8" to the awk process. This is not needed by go-command-chain :)
